#!/usr/bin/env bash

read -p "Show progress? (y/N) " -r progress

if [[ "$progress" = "y" ]]
    then cat data/entry_and_pitch_db.sql | tee /dev/tty | sqlite3 data/data.db;
    else sqlite3 data/data.db < data/entry_and_pitch_db.sql;
fi

